<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>1.0.0</Version>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>

        <!-- NuGet Packaging -->
        <PackageId>AndanteTribe.MasterSystem.Abstractions</PackageId>
        <PackageVersion>$(Version)</PackageVersion>
        <Authors>AndanteTribe</Authors>
        <Copyright>© AndanteTribe</Copyright>
        <Description>Master data generation pipeline for .NET and Unity.</Description>
        <PackageProjectUrl>https://github.com/AndanteTribe/MasterSystem</PackageProjectUrl>
        <RepositoryUrl>$(PackageProjectUrl)</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

</Project>
